// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl8u3EGDeOLubyUAHPWIf3Q4JKqMgFzAY',
    appId: '1:846801641268:web:c2c4891ebfb6a0e0940f61',
    messagingSenderId: '846801641268',
    projectId: 'luwaas-8417c',
    authDomain: 'luwaas-8417c.firebaseapp.com',
    storageBucket: 'luwaas-8417c.firebasestorage.app',
    measurementId: 'G-4E4G94Y9KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABSo19hzeyhuAtCsO_v8qh-RGSHFPmpPo',
    appId: '1:846801641268:android:9e93e1a18cd6212e940f61',
    messagingSenderId: '846801641268',
    projectId: 'luwaas-8417c',
    authDomain: 'luwaas-8417c.firebaseapp.com',  // ✅ AJOUTE CETTE LIGNE
    storageBucket: 'luwaas-8417c.firebasestorage.app',
  );




  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPNVTUMkJBfFjkqPc1cn_juE6taAEoP1A',
    appId: '1:846801641268:ios:52dd2d78d565f8a4940f61',
    messagingSenderId: '846801641268',
    projectId: 'luwaas-8417c',
    storageBucket: 'luwaas-8417c.firebasestorage.app',
    iosBundleId: 'com.example.luwaas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPNVTUMkJBfFjkqPc1cn_juE6taAEoP1A',
    appId: '1:846801641268:ios:52dd2d78d565f8a4940f61',
    messagingSenderId: '846801641268',
    projectId: 'luwaas-8417c',
    storageBucket: 'luwaas-8417c.firebasestorage.app',
    iosBundleId: 'com.example.luwaas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl8u3EGDeOLubyUAHPWIf3Q4JKqMgFzAY',
    appId: '1:846801641268:web:84d63bff1f27a0d8940f61',
    messagingSenderId: '846801641268',
    projectId: 'luwaas-8417c',
    authDomain: 'luwaas-8417c.firebaseapp.com',
    storageBucket: 'luwaas-8417c.firebasestorage.app',
    measurementId: 'G-31XL94GCX8',
  );
}
